"""Shared starter question catalog for seeding and teacher import."""

from app.models import BloomLevel, Language
from app.services.bloom import DEFAULT_RUBRIC

STARTER_QUESTIONS: list[tuple[str, Language, BloomLevel, str, str, list[dict]]] = [
    (
        "Sum of Two Numbers",
        Language.PYTHON,
        BloomLevel.APPLY,
        "Write a function `add(a, b)` that returns the sum of two integers.",
        "def add(a, b):\n    # your code\n    pass\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Valid Parentheses",
        Language.PYTHON,
        BloomLevel.ANALYZE,
        "Given a string of brackets `()[]{}`, return True if valid and balanced.",
        "def is_valid(s: str) -> bool:\n    # your code\n    pass\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Longest Substring Without Repeating",
        Language.PYTHON,
        BloomLevel.CREATE,
        "Return the length of the longest substring without repeating characters.",
        "def length_of_longest_substring(s: str) -> int:\n    # your code\n    pass\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Hello Method",
        Language.JAVA,
        BloomLevel.APPLY,
        "Write a method `greet(String name)` that returns `Hello, {name}!`.",
        "public class Solution {\n  public String greet(String name) {\n    // your code\n    return null;\n  }\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Binary Search",
        Language.JAVA,
        BloomLevel.ANALYZE,
        "Implement binary search on a sorted int array. Return index or -1.",
        "public class Solution {\n  public int search(int[] nums, int target) {\n    // your code\n    return -1;\n  }\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "LRU Cache Sketch",
        Language.JAVA,
        BloomLevel.CREATE,
        "Sketch an LRU cache with get/put in O(1) average. Explain structure in comments if needed.",
        "public class LRUCache {\n  public LRUCache(int capacity) {}\n  public int get(int key) { return -1; }\n  public void put(int key, int value) {}\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Max of Array",
        Language.CPP,
        BloomLevel.APPLY,
        "Write a function that returns the maximum value in a vector of ints.",
        "#include <vector>\nint max_value(const std::vector<int>& a) {\n  // your code\n  return 0;\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Reverse Linked List Idea",
        Language.CPP,
        BloomLevel.ANALYZE,
        "Write a function reversing a singly linked list (node struct provided).",
        "struct Node { int val; Node* next; };\nNode* reverse(Node* head) {\n  // your code\n  return head;\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Dijkstra Outline",
        Language.CPP,
        BloomLevel.CREATE,
        "Implement Dijkstra for a weighted adjacency list; return dist vector.",
        "#include <vector>\n#include <queue>\nstd::vector<long long> dijkstra(int n, const std::vector<std::vector<std::pair<int,int>>>& g, int src) {\n  // your code\n  return {};\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Semantic Card",
        Language.HTML,
        BloomLevel.UNDERSTAND,
        "Create semantic HTML for a profile card with name, role, and a short bio.",
        "<article>\n  <!-- your markup -->\n</article>\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Responsive Nav",
        Language.CSS,
        BloomLevel.APPLY,
        "Write CSS for a horizontal nav that collapses nicely on small screens (flex/grid).",
        "nav {\n  /* your styles */\n}\n",
        DEFAULT_RUBRIC,
    ),
    (
        "Todo Filter",
        Language.JAVASCRIPT,
        BloomLevel.ANALYZE,
        "Implement `filterTodos(todos, query)` returning items whose title contains query (case-insensitive).",
        "function filterTodos(todos, query) {\n  // todos: [{id, title, done}]\n  // your code\n}\n",
        DEFAULT_RUBRIC,
    ),
]
